name: 'Manual Build'

on:

  workflow_dispatch:

jobs:

  # Build and upload artifacts
  build:

    name: 'Build and Upload Artifacts'

    secrets: inherit

    uses: ./.github/workflows/builder.yml
    with:
      branch-name: '${{ github.ref_name }}'
      update-major-version: false
      update-minor-version: false
      update-patch-version: false
      pre-release-type: 'NaN'  # keep pre-release metadata (if defined)
